### PR TITLE
Add Weekly Usage Stats

### PR DESCRIPTION
**Pull request by awadell1**
Adds a Weekly Usage page under about Arjuna with stats on current usage

`dev/usage_cron.sh` is a cron job to be run every Monday to keep the page up to date.

### CODE REVIEW

**Comment by abillscmu** [comment]
This is nice, but I'd rather see it in a separate "Arjuna Status Dashboard" than the documentation. This will also allow for real time statistics to be used. Docs can link to it, or show how to start that dashboard via a command line interface. depending on whether we decide to run it in the background or just on demand. See [https://edf-hpc.github.io/slurm-web/usage.html](https://edf-hpc.github.io/slurm-web/usage.html) or [https://grafana.com/grafana/dashboards/4323](https://grafana.com/grafana/dashboards/4323) for ideas for applications, and I recommend [dash](https://dash.plotly.com) for building the dashboard, but feel free to use whatever you'd like.

**Comment by awadell1** [comment]
This was more in response to "Can you make a script that sends the disk usage to the docs?" + plus me going a bit overboard with the accounting.

The slurm-web dashboard seems like it's more or less a GUI around `sinfo` and `scontrol show`. Whereas this is more focused on ingesting `sacct` and tabulating weekly stats related to utilization and efficiency. I'd say it's closer to the following tools than a dashboard:

- https://github.com/OleHolmNielsen/Slurm_tools/tree/master/slurmacct
- https://github.com/OleHolmNielsen/Slurm_tools/tree/master/slurmreportmonth

**Comment by abillscmu** [comment]
>This was more in response to "Can you make a script that sends the disk usage to the docs?" + plus me going a bit overboard with the accounting.

Disk usage is an extremely small part of the proposed page, and is actually not mentioned anywhere in the explanation. I think that the `motd` is a better solution to the "How much disk space is left on Arjuna?" question anyway, though having a graphical and tabular display of disk usage by user on a dashboard could be nice. In fact, this information is redundant, since anyone on the list-serve (which should be everyone) is getting it every week anyway. 

>The slurm-web dashboard seems like it's more or less a GUI around sinfo and scontrol show. Whereas this is more focused on ingesting sacct and tabulating weekly stats related to utilization and efficiency. I'd say it's closer to the following tools than a dashboard

What you're proposing is a table showing job "efficiency" by user and a few plots showing the distributions of efficiencies that are computed by a weekly cron job for the entire cluster. This information is not actionable because it doesn't offer enough detail for users to improve their jobs' efficiencies. If individual job efficiencies were computed, users could make changes to their code and/or their submission script, and compare between changes to find the ones that are most impactful. It is not explained in the documentation how to show job efficiency for individual jobs (ie how you are computing this). 

I would like to see better readability here too. This table should be sortable and filterable (possible and easy to implement with dash). It's just too long for a static table.

My suggestion would be to kill everything except the documentation about why efficiency is important, merge that with the slurm page we've discussed (also correct the spelling and grammar mistakes in the text) and add details on how to compute job efficiency (or link to slurm docs on how to do so), and separately create a dashboard for users to explore finer grained statistics (some of which could be real-time) including disk usage, job efficiencies, node statuses, queue wait times and whatever else we can come up with.

**Comment by awadell1** [comment]
> Disk usage is an extremely small part of the proposed page

Well I did go overboard😉

> This information is not actionable because it doesn't offer enough detail for users to improve their jobs' efficiencies

Sure, if the problem was one or two jobs at low efficiencies. But that's not what's happening. User's are over-requesting on  time (Or simply not) and memory. Hence the memory eff. for most users is ~0%. This isn't an issue of `--mem 1G` vs `1.1G` it's 100GB vs 10MB. I think the core issue here is a combo of awareness and poor defaults driving massive allocations. (Ie. default timelimit on gpu is unlimited) 

> show job efficiency for individual jobs

The command is `seff` but we don't currently have it as part of our slurm installation, as it came later. I have a modified copy (so it works with our version) at `/home/awadell/.local/bin/seff`, but for here I just compute it from `sacct` directly. 

> I would like to see better readability here too. This table should be sortable and filterable (possible and easy to implement with dash). It's just too long for a static table.

I don't think this is a great use of time given the other issues on Arjuna. Frankly, I've spent way too much on this as is.

> My suggestion would be to kill...

Concur on the intro to slurm page (Although not this week from me), and adding docs to `seff` pending an update of slurm. I don't see the cost/value proposition of a dashboard at this time.

**Pull request closed without merging**
