### PR TITLE
Create performance-issue.md

### PR DESCRIPTION
**Pull request by abillscmu**
Not sure how I want to handle old issues, since everyone might pile on the same ones, so shelving until I decide( probably tomorrow)

### CODE REVIEW

**Comment by awadell1** [comment]
Yesss🙌

I'd drop the contact info, we have their GitHub account after all.

For the MWE and log file, they can also attach it directly to the issue. Which, personally, would be easier to go checkout.

I'd add a new issue label (like "performance") instead of `admin-task`. My thought was to keep that for `sudo` tasks (think new users, disk usage increase, etc)

**Comment by abillscmu** [comment]
Yesss🙌

> I'd drop the contact info, we have their GitHub account after all.
Some users may not use GitHub a lot, and will likely be better contacted via email. 

> For the MWE and log file, they can also attach it directly to the issue. Which, personally, would be easier to go checkout.
It's nice to have access to the dir when you're debugging this because a lot of times if I'm debugging an MWE I'm going to run it interactively. So we should encourage them to do both

I'd add a new issue label (like "performance") instead of admin-task. My thought was to keep that for sudo tasks (think new users, disk usage increase, etc)
> Good point, added maint tag

**Comment by abillscmu** [comment]
I think we're GTG here, maybe we'll make changes to the performance thing if things get out of hand.

**Review by awadell1 — APPROVED** [review]
LGTM

**Pull request merged**
